source :rubygems

gem 'adsf'
gem 'builder'
gem 'compass'
gem 'htmlcompressor'
gem 'kramdown'
gem 'less', '~>2.3.2'
gem 'listen', '~>1.0.3'
gem 'mime-types'
gem 'nanoc', '~>3.6.3'
gem 'pry'
gem 'rb-inotify', '~> 0.9'
gem 'sass', '~> 3.2.2'
gem 'stringex'
gem 'therubyracer', '~>0.11.4'
gem 'uglifier'
gem 'w3c_validators'
gem 'yuicompressor'